name: mangadex_app
description: "A comic reading app (manga, manhwa, etc)."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.15
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
